### ISSUE TITLE
SystemStackError at the end of test suite

### ISSUE THREAD

**Issue by ragesoss** [deep-cover/deep-cover#13] opened 2017-11-06 00:47 UTC
Running the latest version, I get this at the end:

```
Finished in 13 minutes 36 seconds (files took 13 minutes 42 seconds to load)
1166 examples, 0 failures, 12 pending

/home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/base.rb:44:in `block in children_nodes': stack level too deep (SystemStackError)
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/base.rb:44:in `select'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/base.rb:44:in `children_nodes'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/base.rb:56:in `previous_sibling'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/mixin/flow_accounting.rb:54:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/mixin/has_child_handler.rb:40:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/mixin/flow_accounting.rb:20:in `flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/mixin/flow_accounting.rb:58:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/node/mixin/has_child_handler.rb:40:in `child_flow_entry_count'
	 ... 10471 levels...
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-df667fb091db/lib/deep_cover/core_ext/coverage_replacement.rb:17:in `result'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov.rb:82:in `result'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov/configuration.rb:180:in `block in at_exit'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov/defaults.rb:68:in `block in <top (required)>'
/home/sage/.rbenv/versions/2.3.1/bin/ruby -I/home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.0/lib:/home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.0/lib /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by marcandre** [comment] 2017-11-06 01:03
Very interesting (for us 😈 ).
I can't remember last time I said this, but I really wish the stacktrace was longer. It's not enough to know what's going on here 😢 .
I'm going to try and catch that `SystemStackError` add some diagnostics, although it's always tricky to get those, since catching them late means there's very little place left on the stack to handle things...
In the meantime, bets are open: @MaxLap: any idea? I'm betting 5cents it's in a `case` statement.

**Comment by marcandre** [comment] 2017-11-06 01:08
Oh, the app is public? Awesome, we can try to run it on our end and figure things out then!

**Comment by marcandre** [comment] 2017-11-06 03:39
Good news: I'm able to reproduce the issue on my end. I hope to have better news tomorrow :smile:

**Comment by marcandre** [comment] 2017-11-06 20:23
I was sure this was caused by some kind of infinite loop, but turns out it's caused by a 8000 line hash literal in the `domain-name` gem. The stack just isn't deep enough for our current handling of it 😮 
I definitely would not have thought of that problem!
Should have a fix soon.

**Comment by ragesoss** [comment] 2017-11-06 20:33
hahaha. My guess was some sort of `foo.push *bar` where bar is a very long enumerable, just because I learned about the dangers of that the hard way recently.

**Comment by marcandre** [comment] 2017-11-06 20:37
In our case it's because the analyser is asking the last value how many time it has executed. The last value (a string literal that can not raise) asks the last key, which asks the next to last value, etc..., all the way down.

**Comment by marcandre** [comment] 2017-11-07 08:10
So the problem here is twofold. There's a `StackOverflow` and changing the code to be careful about the stack would work, but there's an even bigger issue that analysing the counts for such a literal is in `O(n^2)`. Each call is trivial, but still!
So it was time to implement memoization!
Branch is ready in #14, and the 200K hash works now, but I'd like @MaxLap to check it out before merging.

**Comment by marcandre** [comment] 2017-11-08 19:27
So, the fix has been merged in `master`.
I've integrated some basic profiling for the performance issue and found a problem, at least in the long hash case (`Node#previous_sibling` is O(n) when it could be `O(1)`).

**Comment by marcandre** [comment] 2017-11-09 06:47
Ok, fixed part of the performance issue. The really long hash example now takes less than 3 seconds, two thirds of which are done by the parser.
Now we need to restrict our coverage and analysis to exclude gems (although going through them all was quite nice a source of bugs like this one :smile:)

**Comment by marcandre** [comment] 2017-11-14 04:06
The latest release supports the `path` option, which defaults to `['./lib', './app']`, so things should be pretty quick now. Closing this.

**Closed by marcandre** 2017-11-14 04:06 UTC
