### ISSUE TITLE
deep-cover causing some tests to fail when running rspec

### ISSUE THREAD

**Issue by zs787** [deep-cover/deep-cover#53] opened 2019-06-14 14:30 UTC
Hi guys,

we have updated recently all of our applications to use version 0.7.4 and everything seems to be working fine. However, one particular application has few tests failing when running rspec starting with this one:

```
Failure/Error: RestClient::Request.execute(method: :get, url: url)

NoMethodError:
  undefined method `disable' for false:FalseClass
...
```

and only when running in our CI. We have been debugging this issue for a couple of days but couldn't get anything beyond what I have provided. I know it's not much but we are continuing debugging on our end and would like to see if there is anything you can help us with. 

For the time being we suspect it might be some sort of a gem dependency issue when using the restclient gem; unless you guys are aware of any known issues that might cause such behaviour when using deep-cover with other tools and gems.

**Comment by marcandre** [comment] 2019-06-14 14:49
> only when running in our CI

Do you mean that running the spec suite locally and  also with deep-cover running doesn't produce the same issue??

As for what the issue could be, it is possible that `deep-cover` is screwing up some of the code when instrumenting it and thus changing the resulting expression. It would be very interesting to figure out what code this is. In the example given above, there is `foo.disable` being called, it might be that the code where `foo` gets evaluated is being badly.

**Comment by zs787** [comment] 2019-06-14 15:18
> Do you mean that running the spec suite locally and also with deep-cover running doesn't produce the same issue??

Yes, only when we run rspec in our CI and with dee-cover running is when this problem starts. Locally all looks fine.

**Comment by marcandre** [comment] 2019-06-14 15:25
That doesn't exactly answer my question... "Locally *and with deep-cover running* all looks fine." is what you meant, right?

**Comment by MaxLap** [comment] 2019-06-14 15:34
The first thing I would look into is if there are gems that are different versions in your CI vs locally. I mean your whole bundle.

Basically, the first thing I would want to see is what the code looks like around the exception's site. I assume the line that generates this exception is in your code (and not in a gem). Would it be possible to see that line and those around it? (You can do so by email if you prefer). Without that basic information, it's hard to make suggestions

A full backtrace is also always helpful to help debug this kind of things.

**Comment by zs787** [comment] 2019-06-14 15:47
> That doesn't exactly answer my question... "Locally _and with deep-cover running_ all looks fine." is what you meant, right?

Yes, thats right

**Comment by zs787** [comment] 2019-06-14 15:51
@MaxLap Yes, I did some comparison and can't really see any obvious difference in versions.

As for providing more info and some code we are looking into that to see what we can share.

**Comment by marcandre** [comment] 2019-06-14 15:51
> The first thing I would look into is if there are gems that are different versions in your CI vs locally. I mean your whole bundle.

But the `Gemfile.lock` is checked into version control, no? I'm also assuming that the same version of Ruby is used, right?

**Comment by zs787** [comment] 2019-06-14 16:17
> But the `Gemfile.lock` is checked into version control, no?

yes, it is. And from our initial debugging we do not suspect any version mismatch between what we have in our CI and what we have locally.

And yes the same Ruby version is being used.

By looking deeper into this we suspect that the `rest-client` gem is what throwing this error and not our code. The `foo.disable` seems to be coming from the gem code and that's why it seems to be giving us a hard time debugging this specific issue and getting a full backtrace

**Comment by zs787** [comment] 2019-06-26 13:19
Hi,

Any updates on this issue or have you been able to reproduce it ?
Unfortunately  we couldn't go beyond a certain point in our debugging and would appreciate if you can help.

Thanks

**Comment by MaxLap** [comment] 2019-06-26 16:01
Hello, I ran coverage report using `deep-cover` on the `rest-client` gem's tests and got no issue. That gem doesn't have a single `disable` method. That's the only trail you've given us. At this point, unless you give us an actual reproduction scenario, there is no way for us to help you.

**Comment by zs787** [comment] 2019-07-02 14:41
@MaxLap thank you for taking the time to look into this and sorry for the late response. We are planning to debug this issue further and see if we can provide you with more details that can help you reproduce this on your end.

**Closed** 2020-05-07 18:20 UTC
